"""users jwt

Revision ID: dcf1cbe751f5
Revises: 1c8cacdf6197
Create Date: 2019-11-05 20:42:44.180724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf1cbe751f5'
down_revision = '1c8cacdf6197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token')
        batch_op.drop_column('token_expiration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_expiration', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=32), nullable=True))

    # ### end Alembic commands ###
